-- CRIAÇÃO DAS TABELAS
CREATE TABLE IF NOT EXISTS FORNECEDOR (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    CIDADE VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS PRODUTO (
    ID INT PRIMARY KEY AUTO_INCREMENT, 
    NOME VARCHAR(100) NOT NULL,
    CATEGORIA VARCHAR(50) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL,
    ESTOQUE INT NOT NULL,
    ID_FORNECEDOR INT NOT NULL,
    FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR(ID)
);

CREATE TABLE IF NOT EXISTS CLIENTE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    IDADE INT NOT NULL
);

CREATE TABLE IF NOT EXISTS PEDIDO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DATA_PEDIDO DATE NOT NULL,
    QUANTIDADE_PEDIDO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID)
);

-- INSERÇÃO DE DADOS
INSERT INTO FORNECEDOR (NOME, CIDADE)
VALUES 
('TechBrasil', 'São Paulo'),
('Computech', 'Rio de Janeiro'),
('Moveis&Co', 'Curitiba');

INSERT INTO PRODUTO (NOME, CATEGORIA, PRECO, ESTOQUE, ID_FORNECEDOR)
VALUES
('Celular X', 'Eletrônicos', 2500.00, 30, 1),
('Notebook Y', 'Eletrônicos', 4800.00, 15, 2),
('Mesa de Madeira', 'Móvel', 750.00, 10, 3),
('Cadeira', 'Móvel', 300.00, 25, 3),
('TV 50', 'Eletrônicos', 3500.00, 8, 1);

INSERT INTO CLIENTE (NOME, CIDADE, IDADE)
VALUES
('João Silva', 'São Paulo', 35),
('Maria Santos', 'Belo Horizonte', 28),
('Carlos Lima', 'Rio de Janeiro', 42),
('Fernanda Rocha', 'Curitiba', 30);

INSERT INTO PEDIDO (DATA_PEDIDO, QUANTIDADE_PEDIDO, ID_PRODUTO, ID_CLIENTE)
VALUES
('2024-03-10', 2, 1, 1),
('2024-03-11', 1, 3, 2),
('2024-03-15', 2, 2, 3),
('2024-03-18', 3, 5, 1),
('2024-03-20', 4, 4, 4);

-- CONSULTAS
SELECT * FROM PEDIDO;
SELECT * FROM CLIENTE;
SELECT * FROM PRODUTO;
SELECT * FROM FORNECEDOR;

-- 1. SELECIONAR PRODUTOS DA CATEGORIA 'ELETRÔNICOS' COM PREÇO ACIMA DE R$3000, ORDENADOS DO MAIS CARO PARA O MAIS BARATO 
SELECT * FROM PRODUTO 
WHERE CATEGORIA = 'Eletrônicos' AND PRECO > 3000 
ORDER BY PRECO DESC;

-- 2. ENCONTRAR CLIENTES QUE NÃO MORAM EM SÃO PAULO E TÊM MAIS DE 30 ANOS 
SELECT * FROM CLIENTE 
WHERE CIDADE <> 'São Paulo' AND IDADE > 30;

-- 3. LISTAR PEDIDOS FEITOS ENTRE 10 E 15 DE MARÇO DE 2024, ORDENADOS POR DATA CRESCENTE
SELECT * FROM PEDIDO 
WHERE DATA_PEDIDO BETWEEN '2024-03-10' AND '2024-03-15' 
ORDER BY DATA_PEDIDO ASC;

-- 4. RECUPERAR PRODUTOS COM ESTOQUE MENOR QUE 10 UNIDADES, ORDENADOS POR ESTOQUE CRESCENTE 
SELECT * FROM PRODUTO 
WHERE ESTOQUE < 10 
ORDER BY ESTOQUE ASC;

-- 5. LISTAR FORNECEDORES QUE NÃO ESTÃO NO RIO DE JANEIRO E CUJO NOME COMEÇA COM 'T' 
SELECT * FROM FORNECEDOR 
WHERE CIDADE <> 'Rio de Janeiro' AND NOME LIKE 'T%';

-- 6. CÁLCULO DO PREÇO MÉDIO DOS PRODUTOS POR CATEGORIA
SELECT CATEGORIA, AVG(PRECO) AS PRECO_MEDIO 
FROM PRODUTO 
GROUP BY CATEGORIA;

-- 7. CONTAR QUANTOS PEDIDOS CADA CLIENTE REALIZOU 
SELECT ID_CLIENTE, COUNT(*) AS TOTAL_PEDIDOS 
FROM PEDIDO 
GROUP BY ID_CLIENTE;

-- 8. LISTAR O TOTAL DE PRODUTOS EM ESTOQUE POR CATEGORIA
SELECT CATEGORIA, SUM(ESTOQUE) AS TOTAL_ESTOQUE 
FROM PRODUTO 
GROUP BY CATEGORIA;

-- 9. ENCONTRAR O PEDIDO COM A MAIOR QUANTIDADE DE PRODUTOS COMPRADOS
SELECT ID, QUANTIDADE_PEDIDO 
FROM PEDIDO 
ORDER BY QUANTIDADE_PEDIDO DESC 
LIMIT 1;

-- 10. DESCOBRIR QUANTOS CLIENTES HÁ EM CADA CIDADE, ORDENADOS DO MAIOR PARA O MENOR NÚMERO DE CLIENTES 
SELECT CIDADE, COUNT(*) AS TOTAL_CLIENTES 
FROM CLIENTE 
GROUP BY CIDADE 
ORDER BY TOTAL_CLIENTES DESC;

-- 11. LISTAR PRODUTOS COM SEUS FORNECEDORES 
SELECT P.NOME AS PRODUTO, F.NOME AS FORNECEDOR 
FROM PRODUTO P 
INNER JOIN FORNECEDOR F ON P.ID_FORNECEDOR = F.ID;

-- 12. MOSTRAR PEDIDOS COM O NOME DO CLIENTE E PRODUTO COMPRADO 
SELECT PE.ID AS ID_PEDIDO, C.NOME AS CLIENTE, PR.NOME AS PRODUTO 
FROM PEDIDO PE
INNER JOIN CLIENTE C ON PE.ID_CLIENTE = C.ID
INNER JOIN PRODUTO PR ON PE.ID_PRODUTO = PR.ID
ORDER BY PE.DATA_PEDIDO ASC;

-- 13. AUMENTAR PREÇO DE PRODUTOS DA CATEGORIA 'ELETRÔNICOS' EM 10% 
UPDATE PRODUTO 
SET PRECO = PRECO * 1.10 
WHERE CATEGORIA = 'Eletrônicos';

-- 14. REMOVER PEDIDOS DE CLIENTES QUE MORAM EM CURITIBA 
DELETE FROM PEDIDO 
WHERE ID_CLIENTE IN (
    SELECT ID FROM CLIENTE WHERE CIDADE = 'Curitiba'
);

-- 15. INSERIR NOVO CLIENTE CHAMADO 'RICARDO LOPES'
INSERT INTO CLIENTE (NOME, CIDADE, IDADE) 
VALUES ('Ricardo Lopes', 'Porto Alegre', 38);

-- 16. INSERIR UM NOVO PEDIDO PARA 'JOÃO SILVA' COM 2 NOTEBOOKS NO DIA 25 DE MARÇO DE 2024
INSERT INTO PEDIDO (DATA_PEDIDO, QUANTIDADE_PEDIDO, ID_PRODUTO, ID_CLIENTE)
VALUES (
    '2024-03-25',2,
    (SELECT ID FROM PRODUTO WHERE NOME = 'Notebook Y'),
    (SELECT ID FROM CLIENTE WHERE NOME = 'João Silva')
);